version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: lvnmary/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: lvnmary/kittygram_frontend
    env_file: .env
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: lvnmary/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 9000:80
    depends_on:
      - frontend
      - backend
